branches:
  only:
    - develop

language: node_js
node_js:
    - "0.8"

before_install:
    - npm install -g grunt-cli

before_script:
    - grunt build

notifications:
    email:
        recipients:
            - maxime.cowez@trasysgroup.com
