branches:
  only:
    - master
    - develop

language: node_js
node_js:
    - "0.10"

before_install:
    - npm install -g grunt-cli

script:
    - grunt travis

notifications:
    email:
        recipients:
            - maxime.cowez@trasysgroup.com
            - s.vanmieghem@vmm.be
